version: "3.8"

services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_HOST}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
      interval: 10s
      retries: 5
      timeout: 5s

  mongodb:
    image: mongo:7
    env_file:
      - .env
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      timeout: 5s

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    networks:
      - ${NETWORK_NAME}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      timeout: 5s

  ms-auth:
    build: ./auth
    env_file:
      - .env
    environment:
      SERVER_PORT: 8081

      # Configuração do MongoDB
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB_NAME: auth-db
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASS}

      # Configuração do RabbitMQ
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      # Configuração de Segurança (JWT)
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

    ports:
      - "8081:8081"

    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy

    networks:
      - ${NETWORK_NAME}

  ms-customer:
    build: ./customer
    env_file:
      - .env
    environment:
      SERVER_PORT: 8082

      # Configuração do PostgreSQL
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: customer_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # Configuração do RabbitMQ
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      # Configuração de Segurança (JWT)
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

    ports:
      - "8082:8082"

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      ms-auth:
        condition: service_healthy

    networks:
      - ${NETWORK_NAME}

  ms-employee:
    build: ./employee
    env_file:
      - .env
    environment:
      SERVER_PORT: 8083

      # Configuração do PostgreSQL
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: employee_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # Configuração do RabbitMQ
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      # Configuração de Segurança (JWT)
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

    ports:
      - "8083:8083"

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      ms-auth:
        condition: service_healthy

    networks:
      - ${NETWORK_NAME}

  ms-flight:
    build: ./flight
    env_file:
      - .env
    environment:
      SERVER_PORT: 8084

      # Configuração do PostgreSQL
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: flight_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # Configuração do RabbitMQ
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      # Configuração de Segurança (JWT)
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

    ports:
      - "8084:8084"

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      ms-employee:
        condition: service_healthy

    networks:
      - ${NETWORK_NAME}

  ms-reserve:
    build: ./reserve
    env_file:
      - .env
    environment:
      SERVER_PORT: 8085

      # Configuração do PostgreSQL
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: reserve_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # Configuração do RabbitMQ
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      # Configuração de Segurança (JWT)
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

    ports:
      - "8085:8085"

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      ms-customer:
        condition: service_healthy
      ms-flight:
        condition: service_healthy

    networks:
      - ${NETWORK_NAME}

  saga:
    build: ./saga
    env_file:
      - .env
    environment:
      SERVER_PORT: 8086

      # Configuração do RabbitMQ
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      # Configuração de Segurança (JWT)
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

    ports:
      - "8086:8086"

    depends_on:
      ms-reserve:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    networks:
      - ${NETWORK_NAME}

networks:
  app_network:
    name: ${NETWORK_NAME}

volumes:
  postgres_data:
  mongo_data:
