spring.application.name=customer

server.port=8082

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.profiles.active=dev
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
