spring.application.name=auth
server.port="${SERVER_PORT}"

spring.data.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=${JWT_EXPIRATION}

spring.jpa.properties.hibernate.jdbc.time_zone=UTC